if(NOT LOOM_EXE OR NOT TEST_DIR OR NOT LOOM_VERSION)
    message(FATAL_ERROR "LOOM_EXE, TEST_DIR and LOOM_VERSION are required")
endif()

file(REMOVE_RECURSE "${TEST_DIR}")
execute_process(
    COMMAND "${LOOM_EXE}" new GeneratedApp
        --org com.example
        --directory "${TEST_DIR}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error
)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "loom new failed:\n${output}\n${error}")
endif()

foreach(required
    loom.json
    CMakeLists.txt
    CMakePresets.json
    src/main.cpp
    qml/Main.qml
    qml/components/FeatureCard.qml
    qml/pages/HomePage.qml
    tests/tst_smoke.cpp
    assets
    .idea/QtSettings.xml
    .idea/qmlSettings.xml
)
    if(NOT EXISTS "${TEST_DIR}/${required}")
        message(FATAL_ERROR "Generated project is missing ${required}")
    endif()
endforeach()

file(READ "${TEST_DIR}/loom.json" manifest)
if(NOT manifest MATCHES "com[.]example[.]GeneratedApp")
    message(FATAL_ERROR "Generated manifest did not substitute the application URI")
endif()

# The asset root is globbed wholesale into the binary, so a placeholder README
# there ships inside every application built from the template.
file(GLOB asset_files "${TEST_DIR}/assets/*")
if(asset_files)
    message(FATAL_ERROR
        "The generated assets directory is not empty; these files would be "
        "embedded into every build: ${asset_files}")
endif()

# Not generated by default: the workflow cannot install loom without a
# published release, so shipping one gave every new project a guaranteed red X.
if(EXISTS "${TEST_DIR}/.github")
    message(FATAL_ERROR "loom new generated a CI workflow without --ci github")
endif()

# There is one template and it is loom-styled: the CMake wires the package and
# the QML imports it. This used to be gated behind --loom, with a plain Qt Quick
# template as the default and the two kept in sync by hand.
file(READ "${TEST_DIR}/CMakeLists.txt" generated_cmake)
if(NOT generated_cmake MATCHES "find_package\\(loom ${LOOM_VERSION} CONFIG REQUIRED"
    OR NOT generated_cmake MATCHES "loom::loomplugin")
    message(FATAL_ERROR "loom new did not wire loom into CMakeLists.txt")
endif()
if(NOT generated_cmake MATCHES "find_package\\(loom ${LOOM_VERSION} CONFIG REQUIRED"
    OR NOT generated_cmake MATCHES "NO_DEFAULT_PATH")
    message(FATAL_ERROR
        "loom new did not require its generator version or prefer its own package")
endif()
get_filename_component(loom_exe_dir "${LOOM_EXE}" DIRECTORY)
set(expected_build_tree_config "${loom_exe_dir}/loomConfig.cmake")
if(EXISTS "${expected_build_tree_config}")
    if(NOT generated_cmake MATCHES
        "set\\(_loom_generated_package_hint \"[^\"]+\"\\)")
        message(FATAL_ERROR
            "loom new did not record its build-tree CMake package for direct IDE configure")
    endif()
    # HOME is not set on Windows, where the variable is USERPROFILE. Searching
    # for an empty home leaves the needle as "/", which every generated path
    # matches, so the check has to know it has a home before it runs at all.
    set(user_home "$ENV{HOME}")
    if(user_home STREQUAL "")
        set(user_home "$ENV{USERPROFILE}")
    endif()
    if(NOT user_home STREQUAL "")
        file(TO_CMAKE_PATH "${user_home}" user_home)
        string(FIND "${generated_cmake}" "${user_home}/" leaked_home_position)
        if(NOT leaked_home_position EQUAL -1)
            message(FATAL_ERROR
                "loom new wrote the developer's absolute home path into generated CMake")
        endif()
    endif()
endif()
if(NOT generated_cmake MATCHES "DESIGN")
    message(FATAL_ERROR "loom new did not point loom_add_application at a design file")
endif()

file(READ "${TEST_DIR}/qml/Main.qml" generated_main)
file(READ "${TEST_DIR}/qml/pages/HomePage.qml" generated_home)
file(READ "${TEST_DIR}/qml/components/FeatureCard.qml" generated_card)
if(NOT generated_main MATCHES "import Loom"
    OR NOT generated_home MATCHES "Lo\\.style"
    OR NOT generated_home MATCHES "FeatureCard"
    OR NOT generated_home MATCHES "Loom[.]breakpoint[.]md"
    OR NOT generated_card MATCHES "required property string")
    message(FATAL_ERROR
        "loom new did not generate the responsive multi-file starter")
endif()

# CLion persists these switches per CMake profile. Without this local bootstrap
# the QML language server and its completion provider are both disabled on the
# first open, even though the generated CMake already exposes all import paths.
file(READ "${TEST_DIR}/.idea/qmlSettings.xml" generated_qml_settings)
if(NOT generated_qml_settings MATCHES "myLSPEnabled[^\n]+true"
    OR NOT generated_qml_settings MATCHES "myLSPCompletionEnabled[^\n]+true"
    OR NOT generated_qml_settings MATCHES "entry key=\"Debug\""
    OR NOT generated_qml_settings MATCHES "entry key=\"debug\"")
    message(FATAL_ERROR
        "loom new did not enable CLion QML language-server completion")
endif()

file(READ "${TEST_DIR}/.idea/QtSettings.xml" generated_qt_settings)
get_filename_component(loom_exe_dir "${LOOM_EXE}" DIRECTORY)
set(expected_qmlls "${loom_exe_dir}/qmlls${CMAKE_EXECUTABLE_SUFFIX}")
if(EXISTS "${expected_qmlls}")
    file(TO_CMAKE_PATH "${loom_exe_dir}" expected_qmlls_dir)
    string(FIND "${generated_qt_settings}"
        "myCustomQtBinPath\" value=\"${expected_qmlls_dir}\""
        qmlls_proxy_position)
    if(qmlls_proxy_position EQUAL -1)
        message(FATAL_ERROR
            "loom new did not point CLion at its build-tree qmlls proxy:\n"
            "${generated_qt_settings}")
    endif()
endif()

# The design file the manifest and CMake both point at has to actually exist,
# or the first `loom dev` fails on a missing watch path.
if(NOT EXISTS "${TEST_DIR}/design/tokens.json")
    message(FATAL_ERROR "loom new did not generate design/tokens.json")
endif()

# Placeholders are substituted everywhere, not just in the files that happen to
# be checked above.
foreach(generated_file
    CMakeLists.txt
    .idea/QtSettings.xml
    .idea/qmlSettings.xml
    qml/Main.qml
    qml/components/FeatureCard.qml
    qml/pages/HomePage.qml
    src/main.cpp
    README.md
    design/tokens.json
)
    file(READ "${TEST_DIR}/${generated_file}" generated_contents)
    if(generated_contents MATCHES "@LOOM_")
        message(FATAL_ERROR "loom new left placeholders in ${generated_file}")
    endif()
endforeach()

file(READ "${TEST_DIR}/.gitignore" generated_gitignore)
if(NOT generated_gitignore MATCHES "[.]idea/"
    OR NOT generated_gitignore MATCHES "[.]qmlls[.]ini")
    message(FATAL_ERROR
        "loom new did not keep machine-local editor metadata out of Git")
endif()

set(CI_DIR "${TEST_DIR}-ci")
file(REMOVE_RECURSE "${CI_DIR}")
execute_process(
    COMMAND "${LOOM_EXE}" new GeneratedApp
        --org com.example
        --directory "${CI_DIR}"
        --ci github
    RESULT_VARIABLE ci_result
    OUTPUT_VARIABLE ci_output
    ERROR_VARIABLE ci_error
)
if(NOT ci_result EQUAL 0)
    message(FATAL_ERROR "loom new --ci github failed:\n${ci_output}\n${ci_error}")
endif()
if(NOT EXISTS "${CI_DIR}/.github/workflows/ci.yml")
    message(FATAL_ERROR "loom new --ci github did not generate a workflow")
endif()
if(NOT ci_output MATCHES "TODO")
    message(FATAL_ERROR
        "loom new --ci github did not say the workflow needs completing:\n${ci_output}")
endif()

execute_process(
    COMMAND "${LOOM_EXE}" new GeneratedApp
        --org com.example
        --directory "${TEST_DIR}-badci"
        --ci gitlab
    RESULT_VARIABLE bad_ci_result
    OUTPUT_VARIABLE bad_ci_output
    ERROR_VARIABLE bad_ci_error
)
if(NOT bad_ci_result EQUAL 2)
    message(FATAL_ERROR
        "an unknown --ci provider should be a usage error (exit 2), got "
        "${bad_ci_result}")
endif()
