if(NOT LOOM_EXE OR NOT TEST_DIR OR NOT LOOM_VERSION)
    message(FATAL_ERROR "LOOM_EXE, TEST_DIR and LOOM_VERSION are required")
endif()

file(REMOVE_RECURSE "${TEST_DIR}")
execute_process(
    COMMAND "${LOOM_EXE}" new GeneratedApp
        --org com.example
        --directory "${TEST_DIR}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error
)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "loom new failed:\n${output}\n${error}")
endif()

foreach(required
    loom.json
    CMakeLists.txt
    CMakePresets.json
    src/main.cpp
    qml/Main.qml
    tests/tst_smoke.cpp
    assets
)
    if(NOT EXISTS "${TEST_DIR}/${required}")
        message(FATAL_ERROR "Generated project is missing ${required}")
    endif()
endforeach()

file(READ "${TEST_DIR}/loom.json" manifest)
if(NOT manifest MATCHES "com[.]example[.]GeneratedApp")
    message(FATAL_ERROR "Generated manifest did not substitute the application URI")
endif()

# The asset root is globbed wholesale into the binary, so a placeholder README
# there ships inside every application built from the template.
file(GLOB asset_files "${TEST_DIR}/assets/*")
if(asset_files)
    message(FATAL_ERROR
        "The generated assets directory is not empty; these files would be "
        "embedded into every build: ${asset_files}")
endif()

# Not generated by default: the workflow cannot install loom without a
# published release, so shipping one gave every new project a guaranteed red X.
if(EXISTS "${TEST_DIR}/.github")
    message(FATAL_ERROR "loom new generated a CI workflow without --ci github")
endif()

# There is one template and it is loom-styled: the CMake wires the package and
# the QML imports it. This used to be gated behind --loom, with a plain Qt Quick
# template as the default and the two kept in sync by hand.
file(READ "${TEST_DIR}/CMakeLists.txt" generated_cmake)
if(NOT generated_cmake MATCHES "find_package\\(loom ${LOOM_VERSION} CONFIG REQUIRED"
    OR NOT generated_cmake MATCHES "loom::loomplugin")
    message(FATAL_ERROR "loom new did not wire loom into CMakeLists.txt")
endif()
if(NOT generated_cmake MATCHES "find_package\\(loom ${LOOM_VERSION} CONFIG REQUIRED"
    OR NOT generated_cmake MATCHES "NO_DEFAULT_PATH")
    message(FATAL_ERROR
        "loom new did not require its generator version or prefer its own package")
endif()
get_filename_component(loom_exe_dir "${LOOM_EXE}" DIRECTORY)
set(expected_build_tree_config "${loom_exe_dir}/loomConfig.cmake")
if(EXISTS "${expected_build_tree_config}")
    if(NOT generated_cmake MATCHES
        "set\\(_loom_generated_package_hint \"[^\"]+\"\\)")
        message(FATAL_ERROR
            "loom new did not record its build-tree CMake package for direct IDE configure")
    endif()
    file(TO_CMAKE_PATH "$ENV{HOME}" user_home)
    string(FIND "${generated_cmake}" "${user_home}/" leaked_home_position)
    if(NOT leaked_home_position EQUAL -1)
        message(FATAL_ERROR
            "loom new wrote the developer's absolute home path into generated CMake")
    endif()
endif()
if(NOT generated_cmake MATCHES "DESIGN")
    message(FATAL_ERROR "loom new did not point loom_add_application at a design file")
endif()

file(READ "${TEST_DIR}/qml/Main.qml" generated_main)
if(NOT generated_main MATCHES "import Loom" OR NOT generated_main MATCHES "Lo\\.style")
    message(FATAL_ERROR "loom new did not generate a loom-styled Main.qml")
endif()

# The design file the manifest and CMake both point at has to actually exist,
# or the first `loom dev` fails on a missing watch path.
if(NOT EXISTS "${TEST_DIR}/design/tokens.json")
    message(FATAL_ERROR "loom new did not generate design/tokens.json")
endif()

# Placeholders are substituted everywhere, not just in the files that happen to
# be checked above.
foreach(generated_file
    CMakeLists.txt
    qml/Main.qml
    src/main.cpp
    README.md
    design/tokens.json
)
    file(READ "${TEST_DIR}/${generated_file}" generated_contents)
    if(generated_contents MATCHES "@LOOM_")
        message(FATAL_ERROR "loom new left placeholders in ${generated_file}")
    endif()
endforeach()

set(CI_DIR "${TEST_DIR}-ci")
file(REMOVE_RECURSE "${CI_DIR}")
execute_process(
    COMMAND "${LOOM_EXE}" new GeneratedApp
        --org com.example
        --directory "${CI_DIR}"
        --ci github
    RESULT_VARIABLE ci_result
    OUTPUT_VARIABLE ci_output
    ERROR_VARIABLE ci_error
)
if(NOT ci_result EQUAL 0)
    message(FATAL_ERROR "loom new --ci github failed:\n${ci_output}\n${ci_error}")
endif()
if(NOT EXISTS "${CI_DIR}/.github/workflows/ci.yml")
    message(FATAL_ERROR "loom new --ci github did not generate a workflow")
endif()
if(NOT ci_output MATCHES "TODO")
    message(FATAL_ERROR
        "loom new --ci github did not say the workflow needs completing:\n${ci_output}")
endif()

execute_process(
    COMMAND "${LOOM_EXE}" new GeneratedApp
        --org com.example
        --directory "${TEST_DIR}-badci"
        --ci gitlab
    RESULT_VARIABLE bad_ci_result
    OUTPUT_VARIABLE bad_ci_output
    ERROR_VARIABLE bad_ci_error
)
if(NOT bad_ci_result EQUAL 2)
    message(FATAL_ERROR
        "an unknown --ci provider should be a usage error (exit 2), got "
        "${bad_ci_result}")
endif()
