if(NOT RESPIN_EXE OR NOT TEST_DIR)
    message(FATAL_ERROR "RESPIN_EXE and TEST_DIR are required")
endif()

file(REMOVE_RECURSE "${TEST_DIR}")
execute_process(
    COMMAND "${RESPIN_EXE}" new GeneratedApp
        --org com.example
        --directory "${TEST_DIR}"
    RESULT_VARIABLE result
    OUTPUT_VARIABLE output
    ERROR_VARIABLE error
)
if(NOT result EQUAL 0)
    message(FATAL_ERROR "respin new failed:\n${output}\n${error}")
endif()

foreach(required
    respin.json
    CMakeLists.txt
    CMakePresets.json
    src/main.cpp
    qml/Main.qml
    tests/tst_smoke.cpp
    assets
)
    if(NOT EXISTS "${TEST_DIR}/${required}")
        message(FATAL_ERROR "Generated project is missing ${required}")
    endif()
endforeach()

file(READ "${TEST_DIR}/respin.json" manifest)
if(NOT manifest MATCHES "com[.]example[.]GeneratedApp")
    message(FATAL_ERROR "Generated manifest did not substitute the application URI")
endif()

# The asset root is globbed wholesale into the binary, so a placeholder README
# there ships inside every application built from the template.
file(GLOB asset_files "${TEST_DIR}/assets/*")
if(asset_files)
    message(FATAL_ERROR
        "The generated assets directory is not empty; these files would be "
        "embedded into every build: ${asset_files}")
endif()

# Not generated by default: the workflow cannot install respin without a
# published release, so shipping one gave every new project a guaranteed red X.
if(EXISTS "${TEST_DIR}/.github")
    message(FATAL_ERROR "respin new generated a CI workflow without --ci github")
endif()

# The default template must not reference loom at all: it only appears with
# an explicit --loom.
file(READ "${TEST_DIR}/CMakeLists.txt" default_cmake)
if(default_cmake MATCHES "loom")
    message(FATAL_ERROR "respin new wired loom without --loom")
endif()

set(LOOM_DIR "${TEST_DIR}-loom")
file(REMOVE_RECURSE "${LOOM_DIR}")
execute_process(
    COMMAND "${RESPIN_EXE}" new GeneratedApp
        --org com.example
        --directory "${LOOM_DIR}"
        --loom
    RESULT_VARIABLE loom_result
    OUTPUT_VARIABLE loom_output
    ERROR_VARIABLE loom_error
)
if(NOT loom_result EQUAL 0)
    message(FATAL_ERROR "respin new --loom failed:\n${loom_output}\n${loom_error}")
endif()
file(READ "${LOOM_DIR}/CMakeLists.txt" loom_cmake)
if(NOT loom_cmake MATCHES "find_package\\(loom CONFIG REQUIRED\\)"
    OR NOT loom_cmake MATCHES "loom::loomplugin")
    message(FATAL_ERROR "respin new --loom did not wire loom into CMakeLists.txt")
endif()
# The overlay replaces whole files, so the placeholders it carries must still
# be substituted like the base template's.
if(loom_cmake MATCHES "@RESPIN_")
    message(FATAL_ERROR "respin new --loom left placeholders in CMakeLists.txt")
endif()
file(READ "${LOOM_DIR}/qml/Main.qml" loom_main)
if(NOT loom_main MATCHES "import Loom" OR NOT loom_main MATCHES "Lo\\.style")
    message(FATAL_ERROR "respin new --loom did not generate a loom-styled Main.qml")
endif()
if(loom_main MATCHES "@RESPIN_")
    message(FATAL_ERROR "respin new --loom left placeholders in Main.qml")
endif()
if(NOT loom_output MATCHES "CMAKE_PREFIX_PATH")
    message(FATAL_ERROR
        "respin new --loom did not say how to make loom findable:\n${loom_output}")
endif()

set(CI_DIR "${TEST_DIR}-ci")
file(REMOVE_RECURSE "${CI_DIR}")
execute_process(
    COMMAND "${RESPIN_EXE}" new GeneratedApp
        --org com.example
        --directory "${CI_DIR}"
        --ci github
    RESULT_VARIABLE ci_result
    OUTPUT_VARIABLE ci_output
    ERROR_VARIABLE ci_error
)
if(NOT ci_result EQUAL 0)
    message(FATAL_ERROR "respin new --ci github failed:\n${ci_output}\n${ci_error}")
endif()
if(NOT EXISTS "${CI_DIR}/.github/workflows/ci.yml")
    message(FATAL_ERROR "respin new --ci github did not generate a workflow")
endif()
if(NOT ci_output MATCHES "TODO")
    message(FATAL_ERROR
        "respin new --ci github did not say the workflow needs completing:\n${ci_output}")
endif()

execute_process(
    COMMAND "${RESPIN_EXE}" new GeneratedApp
        --org com.example
        --directory "${TEST_DIR}-badci"
        --ci gitlab
    RESULT_VARIABLE bad_ci_result
    OUTPUT_VARIABLE bad_ci_output
    ERROR_VARIABLE bad_ci_error
)
if(NOT bad_ci_result EQUAL 2)
    message(FATAL_ERROR
        "an unknown --ci provider should be a usage error (exit 2), got "
        "${bad_ci_result}")
endif()
